### ISSUE TITLE
clear on draw

### ISSUE THREAD

**Issue by L2L2L** [martensms/webgl-2d#1]
just wanted to show my support and that there are people... aliens hehehe... could be... out there that wish to see this project back in operations.

I came across the original a few days back and saw that there was a problem with drawing. It would clear the hold screen if you already had something drawn on it. I don't know if you fix this, but I'mma about to see.

**Comment by martensms** [comment]
Thanks for chiming in. Sadly I had no time the last couple months to dig more into merging everything properly. There were many many branches laying around that implemented missing features (but didn't pull request it into the original project). I still want to see this project living and somehow feature complete, at least for some image-based games :)

I also wanted to push this into a more modular architecture, but there's some huge refactoring necessary and I somehow broke it. If you want to dig into that, it's in a new repo because pretty much everything inside the original repo is incompatible with the npm / bower ecosystem: https://github.com/LazerUnicorns/webgl2d

**Comment by L2L2L** [comment]
There seem to be a couple of people who are trying to revive this... Sound great? Wrong... They... um I worry that they'll just die down too. It'll be best to gather you all together to work through it... I think this would be a great way to learn webgl. I like looking through the code though running it.
